name: innenu
description: innenu app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+2

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # https://github.com/brendan-duncan/archive
  archive: ^2.0.13
  # auto_size_text:

  # https://github.com/Baseflow/flutter_cached_network_image
  cached_network_image: ^2.3.3

  # https://github.com/serenader2014/flutter_carousel_slider
  carousel_slider: ^2.3.1

  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.2.1

  # connectivity:
  # device_info:

  # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.10

  # fluttertoast:

  # https://github.com/SunnyApp/flutter_contact
  flutter_contact: ^0.6.4

  # flutter_secure_storage:

  # SVG 支持: https://github.com/dnfield/flutter_svg
  flutter_svg: ^0.19.1

  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.7.7

  # geolocator:
  # location:

  # https://github.com/dart-lang/logging
  logging: ^0.11.4

  # https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.3.2

  # package_info:

  # https://github.com/dart-lang/path
  path: ^1.7.0

  # https://pub.flutter-io.cn/packages/path_provider
  path_provider: ^1.6.24

  # https://github.com/Baseflow/flutter-permission-handler
  permission_handler: ^5.0.1+1
  provider:
  shared_preferences:

  # Flutter shared_preferences plugin util https://github.com/Sky24n/sp_util
  sp_util: ^1.0.1

  url_launcher:
  # video_player:

  # WebView 插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^1.0.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons:
  # flutter_cupertino_localizations:

dev_dependencies:
  build_runner: ^1.10.4
  e2e: ^0.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0
  test:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/components/doc/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
